name: Tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test-html5:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install utest --quiet
          haxelib dev bindable ${{ github.workspace }}
      - name: Set up Node.js dependencies
        working-directory: test/openfl
        run: |
          npm ci
          sudo npx playwright install-with-deps
      - name: Run OpenFL Tests
        working-directory: test/openfl
        run: |
          haxelib run openfl build html5 -final -Dplaywright
          node playwright-runner.js
  test-basic:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install utest --quiet
          haxelib install hxcpp --quiet
          haxelib dev bindable $GITHUB_WORKSPACE
      - name: Run Basic Interpreter Tests
        working-directory: test/basic
        run: haxe test.hxml --interp
      - name: Run Basic Neko Tests
        working-directory: test/basic
        run: |
          haxe test.hxml --neko bin/test.n
          neko bin/test.n
      - name: Run Basic C++ Tests without HXCPP_CHECK_POINTER
        working-directory: test/basic
        run: |
          haxe test.hxml --cpp bin/test
          ./bin/test/Main
      - name: Run Basic C++ Tests with HXCPP_CHECK_POINTER
        working-directory: test/basic
        run: |
          haxe test.hxml --cpp bin/test_check_pointer -D HXCPP_CHECK_POINTER
          ./bin/test_check_pointer/Main
  test-hashlink:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.2]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install utest --quiet
          haxelib dev bindable $GITHUB_WORKSPACE
      - name: Run OpenFL Tests
        working-directory: test/openfl
        run: haxelib run openfl test hl
  test-neko:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install utest --quiet
          haxelib dev bindable $GITHUB_WORKSPACE
      - name: Run OpenFL Tests
        working-directory: test/openfl
        run: haxelib run openfl test neko
  test-air:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.2]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: joshtynjala/setup-adobe-air-action@v2
        with:
          air-version: "33.1"
          accept-license: true
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install utest --quiet
          haxelib dev bindable ${{ github.workspace }} 
          haxelib run lime config AIR_SDK ${{ env.AIR_HOME }}
      - name: Run OpenFL Tests
        working-directory: test/openfl
        run: haxelib run openfl test air
